"""sprints

Revision ID: 571567f7a4b9
Revises: a10237091502
Create Date: 2024-03-31 17:15:29.924435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571567f7a4b9'
down_revision: Union[str, None] = 'a10237091502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('begin', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['team'], ['Teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sprints')
    # ### end Alembic commands ###
