"""tasks

Revision ID: 6f4a9162d580
Revises: 571567f7a4b9
Create Date: 2024-03-31 18:39:40.504730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4a9162d580'
down_revision: Union[str, None] = '571567f7a4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('change_datetime', sa.DateTime(), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.Column('sprint', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['employee'], ['Employees.id'], ),
    sa.ForeignKeyConstraint(['sprint'], ['Sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TaskComments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['Employees.id'], ),
    sa.ForeignKeyConstraint(['task'], ['Tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TaskComments')
    op.drop_table('Tasks')
    # ### end Alembic commands ###
