"""organizations

Revision ID: a10237091502
Revises: fd34a9487e8f
Create Date: 2024-03-24 20:15:33.536636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10237091502'
down_revision: Union[str, None] = 'fd34a9487e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmployeesTree',
    sa.Column('lead', sa.Integer(), nullable=False),
    sa.Column('subordinate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead'], ['Employees.id'], ),
    sa.ForeignKeyConstraint(['subordinate'], ['Employees.id'], ),
    sa.PrimaryKeyConstraint('lead', 'subordinate')
    )
    op.create_table('Teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_lead', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_lead'], ['Employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teams')
    op.drop_table('EmployeesTree')
    # ### end Alembic commands ###
