"""reports

Revision ID: f4374d24c9fa
Revises: 6f4a9162d580
Create Date: 2024-04-02 12:43:53.935675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4374d24c9fa'
down_revision: Union[str, None] = '6f4a9162d580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DateReports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee'], ['Employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SprintReports',
    sa.Column('sprint', sa.Integer(), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee'], ['Employees.id'], ),
    sa.ForeignKeyConstraint(['sprint'], ['Sprints.id'], ),
    sa.PrimaryKeyConstraint('sprint', 'employee')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SprintReports')
    op.drop_table('DateReports')
    # ### end Alembic commands ###
